app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

/* Route model binding */
$router->bind('tasks', function($task_id) {
	return App\Task::whereId($task_id)->first();
});

/* Redirect to authentication */
Route::get('/', function() {
	return redirect('/auth/login');
});

/* Tasks routes */
Route::group(['prefix' => 'tasks', 'as' => 'tasks.'], function() {
    Route::patch('complete/{tasks}',
        ['as' => 'complete', 'uses' => 'TasksController@complete']);
    Route::post('delete_done',
        ['as' => 'destroyDone', 'uses' => 'TasksController@destroyDone']);
});
Route::resource('tasks', 'TasksController', ['except' => ['create']]);

/* Options routes */
Route::group(['prefix' => 'options', 'as' => 'options.'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'OptionsController@index']);
    Route::get('email', 
        ['as' => 'editEmail', 'uses' => 'OptionsController@editEmail']);
    Route::post('email', 
        ['as' => 'updateEmail', 'uses' => 'OptionsController@updateEmail']);
    Route::post('notification', 
        ['as' => 'toggleNotify', 'uses' => 'OptionsController@toggleNotify']);
    Route::get('password', 
        ['as' => 'editPassword', 'uses' => 'OptionsController@editPassword']);
    Route::post('password', 
        ['as' => 'updatePassword', 'uses' => 'OptionsController@updatePassword']);
    Route::get('delete', 
        ['as' => 'confirmDelete', 'uses' => 'OptionsController@confirmDelete']);
    Route::post('delete', 
        ['as' => 'delete', 'uses' => 'OptionsController@deleteAccount']);
});

/* Authentication routes */
Route::get('auth/login', 
    ['as' => 'auth.showLogin', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 
    ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', 
    ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::get('auth/register', 
    ['as' => 'auth.showRegister', 'uses' => 'Auth\AuthController@getRegister']);
Route::post('auth/register', 
    ['as' => 'auth.register', 'uses' => 'Auth\AuthController@postRegister']);

resources/views/email.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Motivado</title>
</head>
<style>
#container {
  max-width: 600px;
  margin: auto;
  font-family: Georgia, Utopia, Charter, serif;
}
#header {
  color: #2780E3;
  width: 100%;
  text-align: center;
  padding-top: 0.5em;
  padding-bottom: 0.5em;
}
.description, .motivation {
  font-weight: bold;
}
.description {
  color: #B5000B;
}
.motivation {
  color: #2780E3;
}
li {
  margin-bottom: 0.5em;
}
footer {
  text-align: center;
  font-size: 0.8em;
  margin-top: 100px;
}
</style>
<body>

<div id="container">

	<h2 id="header"><a href="http://todo.miloszdragan.pl/tasks">MotivaDo</a> reminder</h2>

	@yield('content')

	<footer>
		If you wish to unsubscribe from e-mail notifications, change it in 
		<a href="http://todo.miloszdragan.pl/options">your options</a>.<br>
		If you didn't register on our site, delete this account by clicking <a href="">here</a>.
	</footer>
</div>

</body>
</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>MotivaDo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css"> 
    <link type="text/css" rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/flick/jquery-ui.css"> 
</head>
<body>
<div id="wrap">
  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="{{ route('tasks.index') }}">MotivaDo</a>
      </div>
      <div class="navbar-default" id="navbar-main">
        <ul class="navbar navbar-nav navbar-right">
          <ul class="nav navbar-nav navbar-right">
          @if(isset($user))
            <li><a href="{{ route('options.index') }}">Options</a></li>
            <li><a href="{{ route('auth.logout') }}">Log Out {{ $user->email }}</a></li>
          @else
            <li><a href="{{ route('auth.showRegister') }}">Create Account</a></li>
            <li><a href="{{ route('auth.showLogin') }}">Log In</a></li>
          @endif
          </ul>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    @include('partials._flash')
    @yield('content')
  </div>
</div>
<footer class="footer">
	<h6 class="text-center">
		2015 Miles Dragan | <a href="mailto:miloszdragan@openmailbox.org">miloszdragan@openmailbox.org</a>
	</h6>
</footer>
<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script> 
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> 
<script src="/js/script.js"></script>
</body>
</html>