app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

/* Route model binding */
$router->bind('tasks', function($task_id) {
	return App\Task::whereId($task_id)->first();
});

/* Redirect to authentication */
Route::get('/', function() {
	return redirect('/auth/login');
});

/* Tasks routes */
Route::group(['prefix' => 'tasks', 'as' => 'tasks.'], function() {
    Route::patch('complete/{tasks}',
        ['as' => 'complete', 'uses' => 'TasksController@complete']);
    Route::post('delete_done',
        ['as' => 'destroyDone', 'uses' => 'TasksController@destroyDone']);
});
Route::resource('tasks', 'TasksController', ['except' => ['create']]);

/* Options routes */
Route::group(['prefix' => 'options', 'as' => 'options.'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'OptionsController@index']);
    Route::get('email', 
        ['as' => 'editEmail', 'uses' => 'OptionsController@editEmail']);
    Route::post('email', 
        ['as' => 'updateEmail', 'uses' => 'OptionsController@updateEmail']);
    Route::post('notification', 
        ['as' => 'toggleNotify', 'uses' => 'OptionsController@toggleNotify']);
    Route::get('password', 
        ['as' => 'editPassword', 'uses' => 'OptionsController@editPassword']);
    Route::post('password', 
        ['as' => 'updatePassword', 'uses' => 'OptionsController@updatePassword']);
    Route::get('delete', 
        ['as' => 'confirmDelete', 'uses' => 'OptionsController@confirmDelete']);
    Route::post('delete', 
        ['as' => 'delete', 'uses' => 'OptionsController@deleteAccount']);
});

/* Authentication routes */
Route::get('auth/login', 
    ['as' => 'auth.showLogin', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 
    ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', 
    ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::get('auth/register', 
    ['as' => 'auth.showRegister', 'uses' => 'Auth\AuthController@getRegister']);
Route::post('auth/register', 
    ['as' => 'auth.register', 'uses' => 'Auth\AuthController@postRegister']);

app/Http/Controllers/OptionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Hash;
use Auth;
use App\User;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class OptionsController extends Controller
{
	public function __construct() {
		$this->middleware('auth');
	}

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
		$user = Auth::user();
		$emailNotifications = $user->notify;

		return view('options.index', compact('emailNotifications', 'user'));
    }

    /**
     * Enable or disable getting e-mail notifications
     *
     */
	public function toggleNotify()
	{
		$user = Auth::user();

		$user->notify = $user->notify == 1 ? 0 : 1;
		$user->save();

		return redirect()->route('options.index');
	}

    /**
     * Show form for changing user e-mail address
     *
     */
	public function editEmail()
	{
		$user = Auth::user();

		return view('options.email', compact('user'));
	}

    /**
     * Change user's e-mail address
     *
     */
	public function updateEmail(Request $request)
	{
		$this->validate($request, [
            'email' => 'required|confirmed|email|max:255|unique:users',
			]);

		return redirect()->route('options.index')
			->with(['message' => 'Your settings are saved.', 'status' => 'success']);
	}

    /**
     * Show form for changing user's password
     *
     */
	public function editPassword()
	{
		$user = Auth::user();

		return view('options.password', compact('user'));
	}

    /**
     * Store user's new password
     *
     * TODO: abstract validation
     * TODO: extract to the model
     */
	public function updatePassword(Request $request)
	{
		$this->validate($request, [
            'password' => 'required|confirmed|min:6',
			]);

		$user = Auth::user();
		$user->password = Hash::make($request->password);
		$user->save();

        return redirect()->route('options.index')
            ->with(['message' => 'Your setting are saved.', 'status' => 'success']);
	}

    /**
     * Show page with account delete confirmation
     *
     */
	public function confirmDelete()
	{
		$user = Auth::user();

		return view('options.delete', compact('user'));
	}

    /**
     * Destroy user's account
     *
     */
	public function deleteAccount()
	{
		$user = Auth::user();
		$user->delete();

        return redirect()->route('auth.showLogin')
            ->with(['message' => 'Account deleted.', 'status' => 'info']);
	}
}

resources/views/options/delete.blade.php
@extends('master')

@section('content')
<h3>Delete Account</h3>
<h4 id="delete-warning" class="text-danger">You are going to delete your account. This will permamently delete all your data
from this site.</h4>

<div class="row">
  {!! Form::open(['method' => 'post', 'route' => 'options.delete', 'class' => 'form-horizontal']) !!}
  <button class="btn btn-danger col-lg-2" type="submit">Yes, delete my account</button>
  {!! Form::close() !!}<br>
</div>
<div class="row">
  <a class="btn btn-default col-lg-2" href="{{ route('options.index') }}">No, take me back</a>
</div>
@stop

resources/views/options/email.blade.php
@extends('master')
@section('content')

<h3>Change e-mail address</h3>
<div>
  <p class="help-block">Your current e-mail address: <b>{{ $user->email }}</b></p>
</div>
@include('forms.editEmail')

@stop

resources/views/options/index.blade.php
@extends('master')
@section('content')

	<h3>Options</h3>
	<div class="row">
      <div class="col-lg-5">Your e-mail address: <b>{{ $user->email }}</b></div>
		<a class="btn btn-sm btn-default col-lg-1" href="{{ route('options.editEmail') }}">Change</a>
	</div>
	<div class="row">
		<div class="col-lg-5">Change your password</div>
		<a class="btn btn-sm btn-default col-lg-1" href="{{ route('options.editPassword') }}">Change</a>
	</div>
	<div class="row">
		<div class="col-lg-5">Delete Account</div>
		<a class="btn btn-sm btn-danger col-lg-1" href="{{ route('options.confirmDelete') }}">Delete</a>
	</div>

@stop

resources/views/options/password.blade.php
@extends('master')
@section('content')

<h3>Change password</h3>
<p class="help-block">Password has to be at least 6 characters long.</p>
@include('forms.editPassword')

@stop